// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/3a605075a65f9d994c0878ca16f0151085a9db55/debounce/debounce.d.ts
declare module "debounce" {
	// Overload on boolean constants would allow us to narrow further,
	// but it is not implemented for TypeScript yet
	function f<A extends Function>(f: A, interval?: number, immediate?: boolean): A
	export default f;
}
