export type ADD_CARD = "Card/ADD_CARD";
export const ADD_CARD: ADD_CARD = "Card/ADD_CARD";

export type CARD_TITLE_CHANGED = "Card/CARD_TITLE_CHANGED";
export const CARD_TITLE_CHANGED: CARD_TITLE_CHANGED = "Card/CARD_TITLE_CHANGED";

export type CHANGE_CARD_TITLE = "Card/CHANGE_CARD_TITLE";
export const CHANGE_CARD_TITLE: CHANGE_CARD_TITLE = "Card/CHANGE_CARD_TITLE";

export type ARCHIVE_CARD = "Card/ARCHIVE_CARD";
export const ARCHIVE_CARD: ARCHIVE_CARD = "Card/ARCHIVE_CARD";
