export type HOVERING_CARD = "CardModule/HOVERING_CARD";
export const HOVERING_CARD: HOVERING_CARD = "CardModule/HOVERING_CARD";

export type HOVERING_CARDGROUP = "CardModule/HOVERING_CARDGROUP";
export const HOVERING_CARDGROUP: HOVERING_CARDGROUP = "CardModule/HOVERING_CARDGROUP";
